---

language: python
python: 2.7

install:
    - pip install ansible
    - pip install yamllint
    - pip install ansible-lint

script:
    - yamllint .
    - ansible-lint site.yml
    - ansible-galaxy install -r requirements.yml